apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: django-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql


